&lt;div class=&quot;row&quot;&gt;
&lt;div class=&quot;col-md-12&quot;&gt;
&lt;h3&gt;Standard dan Sertifikasi&lt;/h3&gt;
&lt;/div&gt;
&lt;/div&gt;
&lt;div class=&quot;panel-group&quot;&gt;
&lt;div class=&quot;panel-heading&quot;&gt;
&lt;h1 class=&quot;panel-title&quot;&gt;&lt;a data-toggle=&quot;collapse&quot; href=&quot;#TUVNORD&quot; class=&quot;collapsed&quot; aria-expanded=&quot;false&quot;&gt;&lt;span class=&quot;fa fa-minus-square&quot; aria-hidden=&quot;true&quot;&gt;&lt;/span&gt;&lt;strong&gt;ISO&lt;/strong&gt;&lt;/a&gt;&lt;/h1&gt;
&lt;/div&gt;
&lt;div id=&quot;TUVNORD&quot; class=&quot;panel-collapse collapse&quot; aria-expanded=&quot;false&quot; style=&quot;height: 0px;&quot;&gt;
&lt;div class=&quot;panel-heading&quot;&gt;
&lt;div class=&quot;panel-body&quot;&gt;
&lt;h4 class=&quot;panel-title&quot;&gt;&lt;a data-toggle=&quot;collapse&quot; href=&quot;#ISO9001&quot; class=&quot;collapsed&quot; aria-expanded=&quot;false&quot;&gt;&lt;span class=&quot;fa fa-minus-square&quot; aria-hidden=&quot;true&quot;&gt;&lt;/span&gt;&lt;strong&gt;ISO 9001&lt;/strong&gt;&lt;/a&gt;&lt;/h4&gt;
&lt;/div&gt;
&lt;div id=&quot;ISO9001&quot; class=&quot;panel-collapse collapse&quot; aria-expanded=&quot;false&quot; style=&quot;height: 0px;&quot;&gt;
&lt;div class=&quot;panel-body&quot;&gt;
&lt;p&gt;&lt;/p&gt;
&lt;div class=&quot;row&quot;&gt;
&lt;div class=&quot;col-md-4&quot;&gt;
&lt;div class=&quot;thumbnail&quot;&gt;&lt;a class=&quot;example-image-link&quot; href=&quot;/uploads/Sertifikat-ISO-9001-MGRO18-1.jpg&quot; data-lightbox=&quot;9001&quot; data-title=&quot;Mahkotagroup&quot;&gt;&lt;img class=&quot;example-image&quot; src=&quot;/uploads/Sertifikat-ISO-9001-MGRO18-1.jpg&quot; alt=&quot;&quot; /&gt;&lt;/a&gt;&lt;/div&gt;
&lt;center&gt;&lt;strong&gt;PT Mahkota Group Tbk&lt;/strong&gt;&lt;/center&gt;&lt;/div&gt;

&lt;!-- &lt;div class=&quot;col-md-4&quot;&gt;
&lt;div class=&quot;thumbnail&quot;&gt;&lt;a class=&quot;example-image-link&quot; href=&quot;/uploads/Sertifikat-ISO-9001-MGRO18-1.jpg&quot; data-lightbox=&quot;9001&quot; data-title=&quot;Mahkotagroup&quot;&gt;&lt;img class=&quot;example-image&quot; src=&quot;/uploads/Sertifikat-ISO-9001-MGRO18-1.jpg&quot; alt=&quot;&quot; /&gt;&lt;/a&gt;&lt;/div&gt;
&lt;center&gt;&lt;strong&gt;PT Intan Sejati Andalan&lt;/strong&gt;&lt;/center&gt;&lt;/div&gt; --&gt;

&lt;div class=&quot;col-md-4&quot;&gt;
&lt;div class=&quot;thumbnail&quot;&gt;&lt;a class=&quot;example-image-link&quot; href=&quot;/uploads/BIMS 9001 2021.jpg&quot; data-lightbox=&quot;9001&quot; data-title=&quot;BIMS&quot;&gt;&lt;img class=&quot;example-image&quot; src=&quot;/uploads/BIMS 9001 2021.jpg&quot; alt=&quot;&quot; /&gt;&lt;/a&gt;&lt;/div&gt;
&lt;center&gt;&lt;strong&gt;PT Berlian Inti Mekar&lt;/strong&gt;&lt;/center&gt;&lt;/div&gt;

&lt;div class=&quot;col-md-4&quot;&gt;
&lt;div class=&quot;thumbnail&quot;&gt;&lt;a class=&quot;example-image-link&quot; href=&quot;/uploads/sertifikat/ISO/9001/MUL - 2015.jpeg&quot; data-lightbox=&quot;9001&quot; data-title=&quot;ISA&quot;&gt;&lt;img class=&quot;example-image&quot; src=&quot;/uploads/sertifikat/ISO/9001/MUL - 2015.jpeg&quot; alt=&quot;&quot; /&gt;&lt;/a&gt;&lt;/div&gt;
&lt;center&gt;&lt;strong&gt;PT Mutiara Unggul Lestari&lt;/strong&gt;&lt;/center&gt;&lt;/div&gt;

&lt;/div&gt;
&lt;p&gt;&lt;/p&gt;
&lt;div class=&quot;row&quot;&gt;

&lt;div class=&quot;col-md-4&quot;&gt;
&lt;div class=&quot;thumbnail&quot;&gt;&lt;a class=&quot;example-image-link&quot; href=&quot;/uploads/DPA%209001-2015.jpg&quot; data-lightbox=&quot;9001&quot; data-title=&quot;DPA&quot;&gt;&lt;img class=&quot;example-image&quot; src=&quot;/uploads/DPA%209001-2015.jpg&quot; alt=&quot;&quot; /&gt;&lt;/a&gt;&lt;/div&gt;
&lt;center&gt;&lt;strong&gt;PT Dumai Parcipta Abadi&lt;/strong&gt;&lt;/center&gt;&lt;/div&gt;

&lt;div class=&quot;col-md-4&quot;&gt;
&lt;div class=&quot;thumbnail&quot;&gt;&lt;a class=&quot;example-image-link&quot; href=&quot;/uploads/BIMP 9001 2021.jpg&quot; data-lightbox=&quot;9001&quot; data-title=&quot;BIMP&quot;&gt;&lt;img class=&quot;example-image&quot; src=&quot;/uploads/BIMP 9001 2021.jpg&quot; alt=&quot;&quot; /&gt;&lt;/a&gt;&lt;/div&gt;
&lt;center&gt;&lt;strong&gt;PT Berlian Inti Mekar Palembang&lt;/strong&gt;&lt;/center&gt;&lt;/div&gt;

&lt;div class=&quot;col-md-4&quot;&gt;
&lt;div class=&quot;thumbnail&quot;&gt;&lt;a class=&quot;example-image-link&quot; href=&quot;/uploads/BIMR 9001 2021.jpg&quot; data-lightbox=&quot;9001&quot; data-title=&quot;BIMR&quot;&gt;&lt;img class=&quot;example-image&quot; src=&quot;/uploads/BIMR 9001 2021.jpg&quot; alt=&quot;&quot; /&gt;&lt;/a&gt;&lt;/div&gt;
&lt;center&gt;&lt;strong&gt;PT Berlian Inti Mekar Rengat&lt;/strong&gt;&lt;/center&gt;&lt;/div&gt;
&lt;/div&gt;
&lt;p&gt;&lt;/p&gt;
&lt;div class=&quot;row&quot;&gt;
&lt;div class=&quot;col-md-4&quot;&gt;
&lt;div class=&quot;thumbnail&quot;&gt;&lt;a class=&quot;example-image-link&quot; href=&quot;/uploads/sertifikat/ISO/9001/ISA - 2015.jpeg&quot; data-lightbox=&quot;9001&quot; data-title=&quot;ISA&quot;&gt;&lt;img class=&quot;example-image&quot; src=&quot;/uploads/sertifikat/ISO/9001/ISA - 2015.jpeg&quot; alt=&quot;&quot; /&gt;&lt;/a&gt;&lt;/div&gt;
&lt;center&gt;&lt;strong&gt;PT Intan Sejati Andalan&lt;/strong&gt;&lt;/center&gt;&lt;/div&gt;
&lt;/div&gt;
&lt;/div&gt;
&lt;/div&gt;
&lt;/div&gt;
&lt;div class=&quot;panel-body&quot;&gt;
&lt;div class=&quot;panel-heading&quot;&gt;
&lt;h4 class=&quot;panel-title&quot;&gt;&lt;a data-toggle=&quot;collapse&quot; href=&quot;#ISO14001&quot; class=&quot;collapsed&quot; aria-expanded=&quot;false&quot;&gt;&lt;span class=&quot;fa fa-minus-square&quot; aria-hidden=&quot;true&quot;&gt;&lt;/span&gt;&lt;strong&gt;ISO 14001&lt;/strong&gt;&lt;/a&gt;&lt;/h4&gt;
&lt;div id=&quot;ISO14001&quot; class=&quot;panel-collapse collapse&quot; aria-expanded=&quot;false&quot; style=&quot;height: 0px;&quot;&gt;
&lt;div class=&quot;panel-body&quot;&gt;
&lt;p&gt;&lt;/p&gt;
&lt;div class=&quot;row&quot;&gt;
&lt;div class=&quot;col-md-4&quot;&gt;
&lt;div class=&quot;thumbnail&quot;&gt;&lt;a class=&quot;example-image-link&quot; href=&quot;/uploads/DPA%2014001-2015.jpg&quot; data-lightbox=&quot;14001&quot; data-title=&quot;DPA&quot;&gt;&lt;img class=&quot;example-image&quot; src=&quot;/uploads/DPA%2014001-2015.jpg&quot; alt=&quot;&quot; /&gt;&lt;/a&gt;&lt;/div&gt;
&lt;center&gt;&lt;strong&gt;PT Dumai Parcipta Abadi&lt;/strong&gt;&lt;/center&gt;&lt;/div&gt;
&lt;div class=&quot;col-md-4&quot;&gt;
&lt;div class=&quot;thumbnail&quot;&gt;&lt;a class=&quot;example-image-link&quot; href=&quot;/uploads/Certificate-ISO-14001-BIMS19.jpg&quot; data-lightbox=&quot;14001&quot; data-title=&quot;BIMS&quot;&gt;&lt;img class=&quot;example-image&quot; src=&quot;/uploads/Certificate-ISO-14001-BIMS19.jpg&quot; alt=&quot;&quot; /&gt;&lt;/a&gt;&lt;/div&gt;
&lt;center&gt;&lt;strong&gt;PT Berlian Inti Mekar Siak&lt;/strong&gt;&lt;/center&gt;&lt;/div&gt;
&lt;div class=&quot;col-md-4&quot;&gt;
&lt;div class=&quot;thumbnail&quot;&gt;&lt;a class=&quot;example-image-link&quot; href=&quot;/uploads/sertifikat/ISO/14001/MUL 2015.jpeg&quot; data-lightbox=&quot;14001&quot; data-title=&quot;ISA&quot;&gt;&lt;img class=&quot;example-image&quot; src=&quot;/uploads/sertifikat/ISO/14001/MUL 2015.jpeg&quot; alt=&quot;&quot; /&gt;&lt;/a&gt;&lt;/div&gt;
&lt;center&gt;&lt;strong&gt;PT Mutiara Unggul Lestari&lt;/strong&gt;&lt;/center&gt;&lt;/div&gt;
&lt;/div&gt;
&lt;p&gt;&lt;/p&gt;
&lt;div class=&quot;row&quot;&gt;
&lt;div class=&quot;col-md-4&quot;&gt;
&lt;div class=&quot;thumbnail&quot;&gt;&lt;a class=&quot;example-image-link&quot; href=&quot;/uploads/BIMR 14001 2021.jpg&quot; data-lightbox=&quot;14001&quot; data-title=&quot;BIMR&quot;&gt;&lt;img class=&quot;example-image&quot; src=&quot;/uploads/BIMR 14001 2021.jpg&quot; alt=&quot;&quot; /&gt;&lt;/a&gt;&lt;/div&gt;
&lt;center&gt;&lt;strong&gt;PT Berlian Inti Mekar Palembang&lt;/strong&gt;&lt;/center&gt;&lt;/div&gt;
&lt;div class=&quot;col-md-4&quot;&gt;
&lt;div class=&quot;thumbnail&quot;&gt;&lt;a class=&quot;example-image-link&quot; href=&quot;/uploads/BIMR 14001 2021_1.jpg&quot; data-lightbox=&quot;14001&quot; data-title=&quot;BIMR&quot;&gt;&lt;img class=&quot;example-image&quot; src=&quot;/uploads/BIMR 14001 2021_1.jpg&quot; alt=&quot;&quot; /&gt;&lt;/a&gt;&lt;/div&gt;
&lt;center&gt;&lt;strong&gt;PT Berlian Inti Mekar Rengat&lt;/strong&gt;&lt;/center&gt;&lt;/div&gt;
&lt;div class=&quot;col-md-4&quot;&gt;
&lt;div class=&quot;thumbnail&quot;&gt;&lt;a class=&quot;example-image-link&quot; href=&quot;/uploads/ISA ISO 14001_EN.jpg&quot; data-lightbox=&quot;14001&quot; data-title=&quot;ISA&quot;&gt;&lt;img class=&quot;example-image&quot; src=&quot;/uploads/ISA ISO 14001_EN.jpg&quot; alt=&quot;&quot; /&gt;&lt;/a&gt;&lt;/div&gt;
&lt;center&gt;&lt;strong&gt;PT Intan Sejati Andalan&lt;/strong&gt;&lt;/center&gt;&lt;/div&gt;
&lt;/div&gt;
&lt;/div&gt;
&lt;/div&gt;
&lt;/div&gt;
&lt;/div&gt;
&lt;div class=&quot;panel-body&quot;&gt;
&lt;div class=&quot;panel-heading&quot;&gt;
&lt;h4 class=&quot;panel-title&quot;&gt;&lt;a data-toggle=&quot;collapse&quot; href=&quot;#ISO22000&quot; class=&quot;collapsed&quot; aria-expanded=&quot;false&quot;&gt;&lt;span class=&quot;fa fa-minus-square&quot; aria-hidden=&quot;true&quot;&gt;&lt;/span&gt;&lt;strong&gt;ISO 22000&lt;/strong&gt;&lt;/a&gt;&lt;/h4&gt;
&lt;div id=&quot;ISO22000&quot; class=&quot;panel-collapse collapse&quot; aria-expanded=&quot;false&quot; style=&quot;height: 0px;&quot;&gt;
&lt;div class=&quot;panel-body&quot;&gt;
&lt;p&gt;&lt;/p&gt;
&lt;div class=&quot;row&quot;&gt;
&lt;div class=&quot;col-md-4&quot;&gt;
&lt;div class=&quot;thumbnail&quot;&gt;&lt;a class=&quot;example-image-link&quot; href=&quot;/uploads/DPA%2022000-2018.jpg&quot; data-lightbox=&quot;22000&quot; data-title=&quot;DPA&quot;&gt;&lt;img class=&quot;example-image&quot; src=&quot;/uploads/DPA%2022000-2018.jpg&quot; alt=&quot;&quot; /&gt;&lt;/a&gt;&lt;/div&gt;
&lt;center&gt;&lt;strong&gt;PT Dumai Parcipta Abadi&lt;/strong&gt;&lt;/center&gt;&lt;/div&gt;
&lt;/div&gt;
&lt;/div&gt;
&lt;/div&gt;
&lt;/div&gt;
&lt;/div&gt;
&lt;div class=&quot;panel-body&quot;&gt;
&lt;div class=&quot;panel-heading&quot;&gt;
&lt;h4 class=&quot;panel-title&quot;&gt;&lt;a data-toggle=&quot;collapse&quot; href=&quot;#ISO37001&quot; class=&quot;collapsed&quot; aria-expanded=&quot;false&quot;&gt;&lt;span class=&quot;fa fa-minus-square&quot; aria-hidden=&quot;true&quot;&gt;&lt;/span&gt;&lt;strong&gt;ISO 37001&lt;/strong&gt;&lt;/a&gt;&lt;/h4&gt;
&lt;div id=&quot;ISO37001&quot; class=&quot;panel-collapse collapse&quot; aria-expanded=&quot;false&quot; style=&quot;height: 0px;&quot;&gt;
&lt;div class=&quot;panel-body&quot;&gt;
&lt;p&gt;&lt;/p&gt;
&lt;div class=&quot;row&quot;&gt;
&lt;div class=&quot;col-md-4&quot;&gt;
&lt;div class=&quot;thumbnail&quot;&gt;&lt;a class=&quot;example-image-link&quot; href=&quot;/uploads/antibribery.jpg&quot; data-lightbox=&quot;37001&quot; data-title=&quot;Mahkotagroup&quot;&gt;&lt;img class=&quot;example-image&quot; src=&quot;/uploads/antibribery.jpg&quot; alt=&quot;&quot; /&gt;&lt;/a&gt;&lt;/div&gt;
&lt;center&gt;&lt;strong&gt;PT Mahkota Group Tbk&lt;/strong&gt;&lt;/center&gt;&lt;/div&gt;
&lt;/div&gt;
&lt;/div&gt;
&lt;/div&gt;
&lt;/div&gt;
&lt;/div&gt;
&lt;div class=&quot;panel-body&quot;&gt;
&lt;div class=&quot;panel-heading&quot;&gt;
&lt;h4 class=&quot;panel-title&quot;&gt;&lt;a data-toggle=&quot;collapse&quot; href=&quot;#ISO45001&quot; class=&quot;collapsed&quot; aria-expanded=&quot;false&quot;&gt;&lt;span class=&quot;fa fa-minus-square&quot; aria-hidden=&quot;true&quot;&gt;&lt;/span&gt;&lt;strong&gt;ISO 45001&lt;/strong&gt;&lt;/a&gt;&lt;/h4&gt;
&lt;div id=&quot;ISO45001&quot; class=&quot;panel-collapse collapse&quot; aria-expanded=&quot;false&quot; style=&quot;height: 0px;&quot;&gt;
&lt;div class=&quot;panel-body&quot;&gt;
&lt;p&gt;&lt;/p&gt;
&lt;div class=&quot;row&quot;&gt;
&lt;div class=&quot;col-md-4&quot;&gt;
&lt;div class=&quot;thumbnail&quot;&gt;&lt;a class=&quot;example-image-link&quot; href=&quot;/uploads/ISA ISO 45001_EN.jpg&quot; data-lightbox=&quot;45001&quot; data-title=&quot;ISA&quot;&gt;&lt;img class=&quot;example-image&quot; src=&quot;/uploads/ISA ISO 45001_EN.jpg&quot; alt=&quot;&quot; /&gt;&lt;/a&gt;&lt;/div&gt;
&lt;center&gt;&lt;strong&gt;PT Intan Sejati Andalan&lt;/strong&gt;&lt;/center&gt;&lt;/div&gt;
&lt;/div&gt;
&lt;/div&gt;
&lt;/div&gt;
&lt;/div&gt;
&lt;/div&gt;
&lt;/div&gt;
&lt;div class=&quot;panel-group&quot;&gt;
&lt;div class=&quot;panel-heading&quot;&gt;
&lt;h1 class=&quot;panel-title&quot;&gt;&lt;a data-toggle=&quot;collapse&quot; href=&quot;#penghargaan&quot; class=&quot;collapsed&quot; aria-expanded=&quot;false&quot;&gt;&lt;span class=&quot;fa fa-minus-square&quot; aria-hidden=&quot;true&quot;&gt;&lt;/span&gt;&lt;strong&gt;Certificate of Appreciation&lt;/strong&gt;&lt;/a&gt;&lt;/h1&gt;
&lt;/div&gt;
&lt;div id=&quot;penghargaan&quot; class=&quot;panel-collapse collapse&quot; aria-expanded=&quot;false&quot; style=&quot;height: 0px;&quot;&gt;
&lt;div class=&quot;panel-body&quot;&gt;
&lt;p&gt;&lt;/p&gt;
&lt;div class=&quot;row&quot;&gt;
&lt;div class=&quot;col-md-4&quot;&gt;
&lt;div class=&quot;thumbnail&quot;&gt;&lt;a class=&quot;example-image-link&quot; href=&quot;/uploads/sertifikat/certificate_of_appreciation/CertificateofAppreciationMUL.jpeg&quot; data-lightbox=&quot;penghargaan&quot; data-title=&quot;MUL&quot;&gt;&lt;img class=&quot;example-image&quot; src=&quot;/uploads/sertifikat/certificate_of_appreciation/CertificateofAppreciationMUL.jpeg&quot; alt=&quot;&quot; /&gt;&lt;/a&gt;&lt;/div&gt;
&lt;center&gt;&lt;strong&gt;PT Mutiara Unggul Lestari&lt;/strong&gt;&lt;/center&gt;&lt;/div&gt;
&lt;div class=&quot;col-md-4&quot;&gt;
&lt;div class=&quot;thumbnail&quot;&gt;&lt;a class=&quot;example-image-link&quot; href=&quot;/uploads/sertifikat/certificate_of_appreciation/CertificateofAppreciationISA.jpeg&quot; data-lightbox=&quot;penghargaan&quot; data-title=&quot;ISA&quot;&gt;&lt;img class=&quot;example-image&quot; src=&quot;/uploads/sertifikat/certificate_of_appreciation/CertificateofAppreciationISA.jpeg&quot; alt=&quot;&quot; /&gt;&lt;/a&gt;&lt;/div&gt;
&lt;center&gt;&lt;strong&gt;PT Intan Sejati Andalan&lt;/strong&gt;&lt;/center&gt;&lt;/div&gt;
&lt;div class=&quot;col-md-4&quot;&gt;
&lt;div class=&quot;thumbnail&quot;&gt;&lt;a class=&quot;example-image-link&quot; href=&quot;/uploads/SMK%203%20DPA.jpg&quot; data-lightbox=&quot;penghargaan&quot; data-title=&quot;DPA&quot;&gt;&lt;img class=&quot;example-image&quot; src=&quot;/uploads/SMK%203%20DPA.jpg&quot; alt=&quot;&quot; /&gt;&lt;/a&gt;&lt;/div&gt;
&lt;center&gt;&lt;strong&gt;PT Dumai Parcipta Abadi&lt;/strong&gt;&lt;/center&gt;&lt;/div&gt;
&lt;/div&gt;
&lt;p&gt;&lt;/p&gt;
&lt;div class=&quot;row&quot;&gt;
&lt;div class=&quot;col-md-4&quot;&gt;
&lt;div class=&quot;thumbnail&quot;&gt;&lt;a class=&quot;example-image-link&quot; href=&quot;/uploads/BIMS SMK3 2021.jpg&quot; data-lightbox=&quot;penghargaan&quot; data-title=&quot;BIMS&quot;&gt;&lt;img class=&quot;example-image&quot; src=&quot;/uploads/BIMS SMK3 2021.jpg&quot; alt=&quot;&quot; /&gt;&lt;/a&gt;&lt;/div&gt;
&lt;center&gt;&lt;strong&gt;PT Berlian Inti Mekar Siak&lt;/strong&gt;&lt;/center&gt;&lt;/div&gt;
&lt;div class=&quot;col-md-4&quot;&gt;
&lt;div class=&quot;thumbnail&quot;&gt;&lt;a class=&quot;example-image-link&quot; href=&quot;/uploads/BIMR SMK3 2021.jpg&quot; data-lightbox=&quot;penghargaan&quot; data-title=&quot;BIMR&quot;&gt;&lt;img class=&quot;example-image&quot; src=&quot;/uploads/BIMR SMK3 2021.jpg&quot; alt=&quot;&quot; /&gt;&lt;/a&gt;&lt;/div&gt;
&lt;center&gt;&lt;strong&gt;PT Berlian Inti Mekar Rengat&lt;/strong&gt;&lt;/center&gt;&lt;/div&gt;
&lt;div class=&quot;col-md-4&quot;&gt;
&lt;div class=&quot;thumbnail&quot;&gt;&lt;a class=&quot;example-image-link&quot; href=&quot;/uploads/SMK3 PT BIMP.jpg&quot; data-lightbox=&quot;penghargaan&quot; data-title=&quot;BIMS&quot;&gt;&lt;img class=&quot;example-image&quot; src=&quot;/uploads/SMK3 PT BIMP.jpg&quot; alt=&quot;&quot; /&gt;&lt;/a&gt;&lt;/div&gt;
&lt;center&gt;&lt;strong&gt;PT Berlian Inti Mekar Palembang&lt;/strong&gt;&lt;/center&gt;&lt;/div&gt;
&lt;/div&gt;
&lt;/div&gt;
&lt;/div&gt;
&lt;/div&gt;
&lt;div class=&quot;panel-group&quot;&gt;
&lt;div class=&quot;panel-heading&quot;&gt;
&lt;h1 class=&quot;panel-title&quot;&gt;&lt;a data-toggle=&quot;collapse&quot; href=&quot;#nihil&quot; class=&quot;collapsed&quot; aria-expanded=&quot;false&quot;&gt;&lt;span class=&quot;fa fa-minus-square&quot; aria-hidden=&quot;true&quot;&gt;&lt;/span&gt;&lt;strong&gt;Zero Accident Reward&lt;/strong&gt;&lt;/a&gt;&lt;/h1&gt;
&lt;/div&gt;
&lt;div id=&quot;nihil&quot; class=&quot;panel-collapse collapse&quot; aria-expanded=&quot;false&quot; style=&quot;height: 0px;&quot;&gt;
&lt;div class=&quot;panel-body&quot;&gt;
&lt;p&gt;&lt;/p&gt;
&lt;div class=&quot;row&quot;&gt;
&lt;div class=&quot;col-md-4&quot;&gt;
&lt;div class=&quot;thumbnail&quot;&gt;&lt;a class=&quot;example-image-link&quot; href=&quot;/uploads/zero_isa_2021.jpg&quot; data-lightbox=&quot;nihil&quot; data-title=&quot;ISA&quot;&gt;&lt;img class=&quot;example-image&quot; src=&quot;/uploads/zero_isa_2021.jpg&quot; alt=&quot;&quot; /&gt;&lt;/a&gt;&lt;/div&gt;
&lt;center&gt;&lt;strong&gt;PT Intan Sejati Andalan&lt;/strong&gt;&lt;/center&gt;&lt;/div&gt;
&lt;div class=&quot;col-md-4&quot;&gt;
&lt;div class=&quot;thumbnail&quot;&gt;&lt;a class=&quot;example-image-link&quot; href=&quot;/uploads/zero_mul_2021.jpg&quot; data-lightbox=&quot;nihil&quot; data-title=&quot;MUL&quot;&gt;&lt;img class=&quot;example-image&quot; src=&quot;/uploads/zero_mul_2021.jpg&quot; alt=&quot;&quot; /&gt;&lt;/a&gt;&lt;/div&gt;
&lt;center&gt;&lt;strong&gt;PT Mutiara Unggul Lestari&lt;/strong&gt;&lt;/center&gt;&lt;/div&gt;
&lt;div class=&quot;col-md-4&quot;&gt;
&lt;div class=&quot;thumbnail&quot;&gt;&lt;a class=&quot;example-image-link&quot; href=&quot;/uploads/zero_bims__2021.jpg&quot; data-lightbox=&quot;nihil&quot; data-title=&quot;BIMS&quot;&gt;&lt;img class=&quot;example-image&quot; src=&quot;/uploads/zero_bims__2021.jpg&quot; alt=&quot;&quot; /&gt;&lt;/a&gt;&lt;/div&gt;
&lt;center&gt;&lt;strong&gt;PT Berlian Inti Mekar Siak&lt;/strong&gt;&lt;/center&gt;&lt;/div&gt;
&lt;/div&gt;
&lt;p&gt;&lt;/p&gt;
&lt;/div&gt;
&lt;/div&gt;
&lt;div class=&quot;panel-group&quot;&gt;
&lt;div class=&quot;panel-heading&quot;&gt;
&lt;h1 class=&quot;panel-title&quot;&gt;&lt;a data-toggle=&quot;collapse&quot; href=&quot;#ISPO&quot; class=&quot;collapsed&quot; aria-expanded=&quot;false&quot;&gt;&lt;span class=&quot;fa fa-minus-square&quot; aria-hidden=&quot;true&quot;&gt;&lt;/span&gt;&lt;strong&gt;ISPO&lt;/strong&gt;&lt;/a&gt;&lt;/h1&gt;
&lt;/div&gt;
&lt;div id=&quot;ISPO&quot; class=&quot;panel-collapse collapse&quot; aria-expanded=&quot;false&quot; style=&quot;height: 0px;&quot;&gt;
&lt;div class=&quot;panel-body&quot;&gt;
&lt;p&gt;&lt;/p&gt;
&lt;div class=&quot;row&quot;&gt;
&lt;div class=&quot;col-md-4&quot;&gt;
&lt;div class=&quot;thumbnail&quot;&gt;&lt;a class=&quot;example-image-link&quot; href=&quot;/uploads/1.ISPO BIMP 2022.jpeg&quot; data-lightbox=&quot;ISPO&quot; data-title=&quot;BIMP&quot;&gt;&lt;img class=&quot;example-image&quot; src=&quot;/uploads/1.ISPO BIMP 2022.jpeg&quot; alt=&quot;&quot; /&gt;&lt;/a&gt;&lt;/div&gt;
&lt;center&gt;&lt;strong&gt;PT Berlian Inti Mekar Palembang&lt;/strong&gt;&lt;/center&gt;&lt;/div&gt;&lt;div class=&quot;col-md-4&quot;&gt;
&lt;div class=&quot;thumbnail&quot;&gt;&lt;a class=&quot;example-image-link&quot; href=&quot;/uploads/ISPO BIMR 2021.jpg&quot; data-lightbox=&quot;ISPO&quot; data-title=&quot;BIMS&quot;&gt;&lt;img class=&quot;example-image&quot; src=&quot;/uploads/ISPO BIMR 2021.jpg&quot; alt=&quot;&quot; /&gt;&lt;/a&gt;&lt;/div&gt;
&lt;center&gt;&lt;strong&gt;PT Berlian Inti Mekar Siak&lt;/strong&gt;&lt;/center&gt;&lt;/div&gt;
&lt;/div&gt;
&lt;/div&gt;
&lt;/div&gt;
&lt;/div&gt;
&lt;div class=&quot;panel-group&quot;&gt;
&lt;div class=&quot;panel-heading&quot;&gt;
&lt;h1 class=&quot;panel-title&quot;&gt;&lt;a data-toggle=&quot;collapse&quot; href=&quot;#danlainlain&quot; class=&quot;collapsed&quot; aria-expanded=&quot;false&quot;&gt;&lt;span class=&quot;fa fa-minus-square&quot; aria-hidden=&quot;true&quot;&gt;&lt;/span&gt;&lt;strong&gt;Others&lt;/strong&gt;&lt;/a&gt;&lt;/h1&gt;
&lt;/div&gt;
&lt;div id=&quot;danlainlain&quot; class=&quot;panel-collapse collapse&quot; aria-expanded=&quot;false&quot; style=&quot;height: 0px;&quot;&gt;
&lt;div class=&quot;panel-body&quot;&gt;
&lt;p&gt;&lt;/p&gt;
&lt;div class=&quot;row&quot;&gt;
&lt;div class=&quot;col-md-4&quot;&gt;
&lt;div class=&quot;thumbnail&quot;&gt;&lt;a class=&quot;example-image-link&quot; href=&quot;/uploads/Sertifikat%20AEI.jpg&quot; data-lightbox=&quot;DLL&quot; data-title=&quot;Mahkotagroup&quot;&gt;&lt;img class=&quot;example-image&quot; src=&quot;/uploads/Sertifikat%20AEI.jpg&quot; alt=&quot;&quot; /&gt;&lt;/a&gt;&lt;/div&gt;
&lt;center&gt;&lt;strong&gt;PT Mahkota Group Tbk&lt;/strong&gt;&lt;/center&gt;&lt;/div&gt;
&lt;div class=&quot;col-md-4&quot;&gt;
&lt;div class=&quot;thumbnail&quot;&gt;&lt;a class=&quot;example-image-link&quot; href=&quot;/uploads/SertifikasiTQ-min.jpg&quot; data-lightbox=&quot;DLL&quot; data-title=&quot;Mahkotagroup&quot;&gt;&lt;img class=&quot;example-image&quot; src=&quot;/uploads/SertifikasiTQ-min.jpg&quot; alt=&quot;&quot; /&gt;&lt;/a&gt;&lt;/div&gt;
&lt;center&gt;&lt;strong&gt;PT Mahkota Group Tbk&lt;/strong&gt;&lt;/center&gt;&lt;/div&gt;
&lt;div class=&quot;col-md-4&quot;&gt;
&lt;div class=&quot;thumbnail&quot;&gt;&lt;a class=&quot;example-image-link&quot; href=&quot;/uploads/MUL1.jpg&quot; data-lightbox=&quot;DLL&quot; data-title=&quot;MUL&quot;&gt;&lt;img class=&quot;example-image&quot; src=&quot;/uploads/MUL1.jpg&quot; alt=&quot;&quot; /&gt;&lt;/a&gt;&lt;/div&gt;
&lt;center&gt;&lt;strong&gt;PT Mutiara Unggul Lestari&lt;/strong&gt;&lt;/center&gt;&lt;/div&gt;
&lt;/div&gt;
&lt;div class=&quot;row&quot;&gt;
&lt;div class=&quot;col-md-4&quot;&gt;
&lt;div class=&quot;thumbnail&quot;&gt;&lt;a class=&quot;example-image-link&quot; href=&quot;/uploads/ISA1.jpg&quot; data-lightbox=&quot;DLL&quot; data-title=&quot;ISA&quot;&gt;&lt;img class=&quot;example-image&quot; src=&quot;/uploads/ISA1.jpg&quot; alt=&quot;&quot; /&gt;&lt;/a&gt;&lt;/div&gt;
&lt;center&gt;&lt;strong&gt;PT Intan Sejati Andalan&lt;/strong&gt;&lt;/center&gt;&lt;/div&gt;
&lt;/div&gt;
&lt;/div&gt;
&lt;/div&gt;
&lt;/div&gt;
&lt;/div&gt;
&lt;/div&gt;